import { Montserrat } from 'next/font/google'

import Navigation from '@/components/navigation'

import 'swiper/css'
import './globals.scss'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='ru'>
			<body className={`${montserrat.className} page`}>
				{/* <Sidebar /> */}

				<main>{children}</main>

				<Navigation />
			</body>
		</html>
	)
}
